services:
  database:
    image: postgres:14-bullseye
    restart: unless-stopped
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      # POSTGRES_PASSWORD: django
      # POSTGRES_USER: django
      # POSTGRES_DB: django
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    networks:
      - my_app

  backend:
    build: ./lib_catalog
    restart: unless-stopped
    ports:
      - 8000:8000
    depends_on:
      - database
    networks:
      - my_app

  frontend:
    build: ./frontend
    restart: unless-stopped
    ports:
      - 280:80
    depends_on:
      - backend
    networks:
      - my_app

volumes:
  data:

networks:
  my_app:
