services:
  database:
    image: postgres:14-bullseye
    restart: unless-stopped
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      # POSTGRES_PASSWORD: django
      # POSTGRES_USER: django
      # POSTGRES_DB: django
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER}
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - my_app

  backend:
    build: ./lib_catalog
    restart: unless-stopped
    ports:
      - 8000:8000
    depends_on:
      - database
    healthcheck:
      test: curl --fail http://localhost:8000/api/v1/lib/bbk/ || exit 1
      interval: 10s
      timeout: 5s
      retries: 5      
    networks:
      - my_app

  frontend:
    build: ./frontend
    restart: unless-stopped
    ports:
      - 280:80
    depends_on:
      - backend
    healthcheck:
      test: curl --fail http://localhost:3000 || exit 1
      interval: 10s
      timeout: 5s
      retries:       
    networks:
      - my_app

volumes:
  data:

networks:
  my_app:
